class Post {
  String? authorName;
  String? authorImageUrl;
  String? timeAgo;
  String? imageUrl;

  Post({this.authorName, this.authorImageUrl, this.imageUrl, this.timeAgo});
}

final List<Post> posts = [
  Post(
      authorName: 'Waseem Akram',
      authorImageUrl: "images/1.jpeg",
      timeAgo: '30 min',
      imageUrl: "images/1.jpeg"),
  Post(
      authorName: 'Olivia Taylor',
      authorImageUrl: "images/8.png",
      timeAgo: '10 min',
      imageUrl: "images/post1.jpg"),

  Post(
      authorName: 'Sam Martin',
      authorImageUrl: "images/5.jpg",
      timeAgo: '10 min',
      imageUrl: "images/6.jpg"),


  Post(
      authorName: 'Kyllie Jennifer',
      authorImageUrl: "images/8.png",
      timeAgo: '10 min',
      imageUrl: "images/8.png"),
];

final List<String> stories=[
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/3.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',

  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
  'images/1.jpeg',
  'images/4.jpg',
  'images/5.jpg',
  'images/7.jpg',
];